;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldown.Fireball",DevComment="Fireball 어빌리티의 쿨타임 상태")
+GameplayTagList=(Tag="Data.Damage",DevComment="데미지")
+GameplayTagList=(Tag="GameplayCue.Burn",DevComment="Burn 상태 동안 나이아가라 이펙트 재생")
+GameplayTagList=(Tag="State.Burning",DevComment="적이 현재 Burn 상태인지 검사")

